name: Echo Message

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to echo'
        required: false
        default: 'Hello, GitHub Actions!'  # Default message if not provided via API

jobs:
  echo_job:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Echo a message
        run: echo "Hello, GitHub Actions!"